// Shared color families for saved layouts; artwork changes never replace geometry.
(function(){
 'use strict';
 const palette={w:'White',u:'Blue',b:'Black',r:'Red',g:'Green',c:'Colorless',m:'Multicolor',a:'Artifact',l:'Land'};
 const copy=value=>JSON.parse(JSON.stringify(value,(key,item)=>key==='image'?undefined:item));
 function config(data){return data.templateThemes||{enabled:false,families:[]};}
 function records(data){return [...(config(data).families||[]).flatMap(family=>Object.values(family.variants||{})),...(data.frames||[]).flatMap(frame=>frame.templateTheme?.masks||[])];}
 function colors(value){const text=String(value||'').trim().toLowerCase();if(!text)return[];if(/^(multi|multicolor|multicolored)$/.test(text))return['m'];const names=Object.fromEntries(Object.entries(palette).map(([key,name])=>[name.toLowerCase(),key]));const found=[];for(const token of text.split(/[^a-z]+/).filter(Boolean)){if(names[token])found.push(names[token]);else if(/^[wubrgcmal]+$/.test(token))found.push(...token);else throw Error('Unknown frame color: '+token);}return [...new Set(found)];}
 function selection(fields){const specified=String(fields.color||'').trim();const leftColors=colors(fields.frameLeftColor||''),rightColors=colors(fields.frameRightColor||'');if(leftColors.length>1||rightColors.length>1)throw Error('Frame Left/Right Color each require one color.');const left=leftColors[0],right=rightColors[0];if(left)return{left,right:right||'',requested:true};if(right)throw Error('Frame Right Color requires Frame Left Color.');const base=colors(specified||fields.colorIdentity||'');if(!base.length)return{requested:false};return{left:base.length>2?'m':base[0],right:base.length===2?base[1]:'',requested:true};}
 function image(src){return new Promise((resolve,reject)=>{const value=new Image();value.crossOrigin='anonymous';value.onload=()=>resolve(value);value.onerror=()=>reject(Error('Could not load a theme asset.'));value.src=typeof fixUri==='function'?fixUri(src):src;});}
 function canvas(w,h){const value=document.createElement('canvas');value.width=Math.max(1,Math.round(w));value.height=Math.max(1,Math.round(h));return value;}
 async function raster(record,region){const src=await image(record.src),w=src.naturalWidth||src.width,h=src.naturalHeight||src.height,b=region||{x:0,y:0,width:1,height:1},result=canvas(w*b.width,h*b.height);result.getContext('2d').drawImage(src,w*b.x,h*b.y,w*b.width,h*b.height,0,0,result.width,result.height);return result;}
 async function compose(family,link,choice,data,frame){
  const left=link.side==='right'?(choice.right||choice.left):choice.left,right=link.side==='full'?choice.right:'';
  const a=family.variants?.[left],b=right?family.variants?.[right]:null;
  if(!a||right&&!b)throw Error('Asset family “'+family.name+'” is missing '+(!a?palette[left]:palette[right])+'.');
  const source=await raster(a,link.sourceRegion);if(!b)return source.toDataURL();
  const second=await raster(b,link.sourceRegion),normalized=canvas(source.width,source.height);normalized.getContext('2d').drawImage(second,0,0,source.width,source.height);
  const ctx=source.getContext('2d'),first=ctx.getImageData(0,0,source.width,source.height),other=normalized.getContext('2d').getImageData(0,0,source.width,source.height),mask=await image('/img/frames/maskRightHalf.png'),weights=canvas(source.width,source.height);const bounds=frame.bounds||{x:0,y:0,width:1,height:1};weights.getContext('2d').drawImage(mask,bounds.x*mask.width,bounds.y*mask.height,bounds.width*mask.width,bounds.height*mask.height,0,0,source.width,source.height);const alpha=weights.getContext('2d').getImageData(0,0,source.width,source.height).data;
  for(let i=0;i<first.data.length;i+=4){const t=alpha[i+3]/255,aa=first.data[i+3]/255*(1-t),ba=other.data[i+3]/255*t,total=aa+ba;for(let j=0;j<3;j++)first.data[i+j]=total?(first.data[i+j]*aa+other.data[i+j]*ba)/total:0;first.data[i+3]=total*255;}ctx.putImageData(first,0,0);return source.toDataURL();
 }
 async function apply(data,fields,warnings=[]){
  const settings=config(data);if(!settings.enabled)return data;const choice=selection(fields);if(!choice.requested)return data;
  const changes=[];
  for(const frame of data.frames||[]){const link=frame.templateTheme;if(!link)continue;const family=settings.families.find(family=>family.id===link.familyId);if(!family)throw Error('Missing asset family for '+frame.name+'.');changes.push({frame,src:await compose(family,link,choice,data,frame)});}
  if(!changes.length)throw Error('This template has color switching enabled but no linked layers.');
  for(const {frame,src} of changes){frame.src=src;delete frame.image;delete frame.assetId;frame.masks=copy(frame.templateTheme.masks||[]);if(frame.sectionAppearance){frame.sectionAppearance.left=choice.left;frame.sectionAppearance.right=choice.right;}if(frame.sectionCrown){frame.sectionCrown.left=choice.left;frame.sectionCrown.right=choice.right;}if(frame.sectionModule){frame.sectionModule.left=choice.left;frame.sectionModule.right=choice.right;}}
  data.csvImport=data.csvImport||{};data.csvImport.templateColors=[choice.left,choice.right].filter(Boolean);return data;
 }
 const fieldLabel=value=>String(value||'').trim().toLowerCase().replace(/\s+/g,' ');
 function mapFields(data,values,warnings){for(const [label,lines] of Object.entries(values||{})){const matches=Object.values(data.text||{}).filter(field=>fieldLabel(field.csvFieldLabel||field.name)===label);if(matches.length!==1){warnings.push('Template field “'+label+'” '+(matches.length?'is ambiguous; give the fields distinct labels.':'was not found.'));continue;}matches[0].text=lines.join('\n');}}
 function refresh(){const panel=document.querySelector('#template-theme-tools');if(!panel)return;const settings=config(card),layer=panel.querySelector('[data-layer]'),family=panel.querySelector('[data-family]'),oldLayer=layer.value,oldFamily=family.value;layer.innerHTML='';family.innerHTML='';for(const frame of card.frames||[]){const option=document.createElement('option');option.value=ensureDesignLayerId(frame);option.textContent=frame.name;layer.appendChild(option);}for(const item of settings.families){const option=document.createElement('option');option.value=item.id;option.textContent=item.name;family.appendChild(option);}if([...layer.options].some(item=>item.value===oldLayer))layer.value=oldLayer;if([...family.options].some(item=>item.value===oldFamily))family.value=oldFamily;panel.querySelector('[data-enabled]').checked=!!settings.enabled;showFamily();showLayer();}
 function save(action,label){const before=createDesignStateSnapshot();card.templateThemes=card.templateThemes||{enabled:false,families:[]};action(card.templateThemes);commitDesignUndoSnapshot(before,label);refresh();}
 function selectedFamily(){const panel=document.querySelector('#template-theme-tools');return config(card).families.find(family=>family.id===panel.querySelector('[data-family]').value);}
 function showFamily(){const panel=document.querySelector('#template-theme-tools'),family=selectedFamily();panel.querySelector('[data-status]').textContent=family?'Available colors: '+Object.keys(family.variants||{}).map(key=>palette[key]).join(', '):'Create an asset family, then upload its color versions.';}
 function showLayer(){const panel=document.querySelector('#template-theme-tools'),frame=card.frames.find(frame=>frame.designLayerId===panel.querySelector('[data-layer]').value),link=frame?.templateTheme;panel.querySelector('[data-side]').value=link?.side||'full';panel.querySelector('[data-region]').checked=!!link?.sourceRegion;for(const key of ['x','y','width','height'])panel.querySelector('[data-'+key+']').value=link?.sourceRegion?.[key]??(key==='width'||key==='height'?1:0);}
 function mount(){const slot=document.querySelector('#frame-design-element-tools > .frame-design-section-body');if(!slot)return;const panel=document.createElement('details');panel.id='template-theme-tools';panel.className='frame-design-subsection';panel.innerHTML='<summary>Template Colors</summary><div class="frame-design-section-body"><label><input type="checkbox" data-enabled> Enable CSV color switching for this layout</label><p>Families contain interchangeable color artwork. Linking a layer preserves its position, size and text behavior.</p><label>Asset family<select class="input" data-family></select></label><input class="input" data-name placeholder="New family name, e.g. Boss Pinline"><button class="input" type="button" data-create>Create Asset Family</button><label>Upload color<select class="input" data-color></select><input class="input" type="file" accept="image/*" data-upload></label><p data-status aria-live="polite"></p><label>Frame layer<select class="input" data-layer></select></label><button class="input" type="button" data-capture>Use Layer Artwork for Selected Color</button><button class="input" type="button" data-stock>Add Available Stock Colors</button><label>Color behavior<select class="input" data-side><option value="full">Single color or blended two colors</option><option value="left">Left color (keep existing masks)</option><option value="right">Right color (keep existing masks)</option></select></label><details><summary>Source region (advanced)</summary><p>Use this when uploading a complete frame rather than an image of this element. Coordinates are fractions of the source image, from 0 to 1. Each color version must use the same source layout.</p><label><input type="checkbox" data-region> Crop a region of the uploaded image</label><div class="input-grid"><input type="number" min="0" max="1" step=".001" class="input" data-x aria-label="Source X"><input type="number" min="0" max="1" step=".001" class="input" data-y aria-label="Source Y"><input type="number" min=".001" max="1" step=".001" class="input" data-width aria-label="Source width"><input type="number" min=".001" max="1" step=".001" class="input" data-height aria-label="Source height"></div></details><div class="input-grid"><button class="input" type="button" data-link>Link Layer to Family</button><button class="input" type="button" data-unlink>Keep Layer Fixed</button></div><p>Save or export the frame project after linking assets. CSV uses Template plus Color, or explicit Frame Left Color / Frame Right Color. More than two colors use the Multicolor variant.</p></div>';slot.appendChild(panel);
  for(const [key,label] of Object.entries(palette)){const option=document.createElement('option');option.value=key;option.textContent=label;panel.querySelector('[data-color]').appendChild(option);}
  panel.querySelector('[data-family]').onchange=showFamily;panel.querySelector('[data-layer]').onchange=showLayer;
  panel.querySelector('[data-enabled]').onchange=event=>save(settings=>{settings.enabled=event.target.checked;},'Change template color switching');
  panel.querySelector('[data-create]').onclick=()=>{const name=panel.querySelector('[data-name]').value.trim();if(!name)return;const id='theme-'+Date.now().toString(36);save(settings=>settings.families.push({id,name,variants:{}}),'Create color family');panel.querySelector('[data-family]').value=id;showFamily();};
  panel.querySelector('[data-upload]').onchange=async event=>{const family=selectedFamily(),file=event.target.files[0],color=panel.querySelector('[data-color]').value;if(!family||!file)return;try{const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});await image(src);save(()=>{family.variants[color]={name:family.name+' '+palette[color],src};},'Add color variant');}catch(error){panel.querySelector('[data-status]').textContent=error.message||'Could not load the asset.';}event.target.value='';};
  panel.querySelector('[data-capture]').onclick=()=>{const frame=card.frames.find(frame=>frame.designLayerId===panel.querySelector('[data-layer]').value),family=selectedFamily(),color=panel.querySelector('[data-color]').value;if(!frame||!family)return;save(()=>{family.variants[color]={name:family.name+' '+palette[color],src:frame.src};},'Capture color variant');};
  panel.querySelector('[data-stock]').onclick=async()=>{const frame=card.frames.find(frame=>frame.designLayerId===panel.querySelector('[data-layer]').value),family=selectedFamily();if(!frame||!family)return;const variants={};try{for(const color of Object.keys(palette)){let src;if(frame.sectionAppearance?.role==='rules'&&frame.sectionAppearance.style!=='browse'){const style=window.FrameSectionCatalog?.styles.find(item=>item.id===frame.sectionAppearance.style);if(!style?.variants[color])continue;src=(await FrameSectionTools.renderStyle(style,'rules',color,'',!!frame.sectionAppearance.pinlines,false)).src;}else if(card.frames.some(owner=>owner.sectionModule?.partId===frame.designLayerId)||frame.prototypePiece){const style=window.FrameSectionCatalog?.styles.find(item=>item.id==='prototype');if(!style?.variants[color])continue;const owner=card.frames.find(owner=>owner.sectionModule?.partId===frame.designLayerId||owner.designLayerId===frame.prototypePiece?.owner),rendered=await FrameSectionTools.renderPrototype(color,'',owner?.sectionModule?.pinlines!==false);src=frame.prototypePiece?rendered.extras[frame.prototypePiece.kind].src:rendered.src;}else if(/(?:m15PT|\/pt)[WUBRGMALC]\.png$/i.test(frame.src)){src=frame.src.replace(/[WUBRGMALC]\.png$/i,color.toUpperCase()+'.png');try{await image(src);}catch{continue;}}else throw Error('For this custom layer, upload matching color images or capture its artwork for each color.');if(frame.resizeContainerRaster&&frame.image&&window.ContainerResizeTools){const uploaded=await image(src);src=ContainerResizeTools.slices(uploaded,frame.image.naturalWidth||frame.image.width,frame.image.naturalHeight||frame.image.height).toDataURL();}variants[color]={name:family.name+' '+palette[color],src};}if(!Object.keys(variants).length)throw Error('No stock color variants are available for this layer.');save(()=>Object.assign(family.variants,variants),'Add stock color variants');}catch(error){panel.querySelector('[data-status]').textContent=error.message;}};
  panel.querySelector('[data-link]').onclick=()=>{const frame=card.frames.find(frame=>frame.designLayerId===panel.querySelector('[data-layer]').value),family=selectedFamily();if(!frame||!family)return;let sourceRegion;if(panel.querySelector('[data-region]').checked){sourceRegion=Object.fromEntries(['x','y','width','height'].map(key=>[key,Number(panel.querySelector('[data-'+key+']').value)]));if(Object.values(sourceRegion).some(value=>!Number.isFinite(value))||sourceRegion.x<0||sourceRegion.y<0||sourceRegion.width<=0||sourceRegion.height<=0||sourceRegion.x+sourceRegion.width>1||sourceRegion.y+sourceRegion.height>1){panel.querySelector('[data-status]').textContent='The source region must fit inside the image.';return;}}save(()=>{frame.templateTheme={familyId:family.id,side:panel.querySelector('[data-side]').value,sourceRegion,masks:copy(frame.masks||[])};},'Link frame color family');};
  panel.querySelector('[data-unlink]').onclick=()=>{const frame=card.frames.find(frame=>frame.designLayerId===panel.querySelector('[data-layer]').value);if(frame)save(()=>{delete frame.templateTheme;},'Keep frame appearance fixed');};refresh();
 }
 function restore(frame,definition){if((frame.templateTheme||definition.templateTheme)&&frame.src!==definition.src){frame.src=definition.src;frame.masks=copy(definition.masks||[]);if(definition.assetId)frame.assetId=definition.assetId;else delete frame.assetId;Promise.all([image(frame.src).then(asset=>frame.image=asset),...frame.masks.map(async mask=>mask.image=await image(mask.src))]).then(()=>{if(typeof drawFrames==='function')drawFrames();}).catch(error=>console.error(error));}if(definition.templateTheme)frame.templateTheme=copy(definition.templateTheme);else delete frame.templateTheme;}
 window.TemplateThemes={apply,records,colors,selection,fieldLabel,mapFields,refresh,restore};window.addEventListener('frameprojectschanged',refresh);window.addEventListener('frameworkspacechanged',refresh);window.addEventListener('creatortabchanged',refresh);
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
