const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createCanvas,loadImage}=require('@napi-rs/canvas');
const source=fs.readFileSync('js/creator-23.js','utf8');
const context={document:{createElement:()=>createCanvas(1,1)}};
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function cardImageExportCanvas('),source.indexOf('function downloadCard(')),context);
const landscape=createCanvas(6,4),ctx=landscape.getContext('2d');
ctx.fillStyle='red';ctx.fillRect(0,0,3,2);ctx.fillStyle='green';ctx.fillRect(3,0,3,2);
ctx.fillStyle='blue';ctx.fillRect(0,2,3,2); // Bottom right deliberately transparent.
const original=landscape.toBuffer('image/png');context.cardCanvas=landscape;
const output=context.cardImageExportCanvas();
assert.equal(output.width,4);assert.equal(output.height,6);
const pixel=(x,y)=>Array.from(output.getContext('2d').getImageData(x,y,1,1).data);
assert.deepEqual(pixel(3,0),[255,0,0,255],'Top left rotates to top right');
assert.deepEqual(pixel(3,5),[0,128,0,255],'Top right rotates to bottom right');
assert.deepEqual(pixel(0,0),[0,0,255,255],'Bottom left rotates to top left');
assert.deepEqual(pixel(0,5),[0,0,0,0],'Transparency survives rotation');
assert.deepEqual(landscape.toBuffer('image/png'),original,'Editor canvas stays untouched');
const portrait=createCanvas(4,6),square=createCanvas(4,4);
assert.equal(context.cardImageExportCanvas(portrait),portrait);assert.equal(context.cardImageExportCanvas(square),square);
assert.ok(source.includes("exportCanvas.toDataURL('image/jpeg', 0.8)"));
assert.ok(source.includes("exportCanvas.toDataURL('image/png')"));
assert.ok(source.includes("cardImageExportCanvas().toDataURL('image/png').split(',')[1]"),'Saved-card ZIP uses rotated raster');
const builder=fs.readFileSync('js/csvCardBuilder.js','utf8');
const batch={prepareBatchCard:async()=>{},canvasToBlob:canvas=>canvas,cardImageExportCanvas:()=>output};
vm.createContext(batch);vm.runInContext(builder.slice(builder.indexOf('async function renderBatchCard('),builder.indexOf('function facesForResult(')),batch);
(async()=>{assert.equal(await batch.renderBatchCard({},'back'),output,'CSV front/back PNG exports use rotated raster');
const png=await loadImage(output.toBuffer('image/png')),jpg=await loadImage(output.toBuffer('image/jpeg'));
assert.equal(png.width,4);assert.equal(png.height,6);assert.equal(jpg.width,4);assert.equal(jpg.height,6);
console.log('PASS: clockwise pixel mapping, PNG/JPEG dimensions, alpha preservation, untouched source, portrait passthrough and CSV/ZIP export paths.');
})().catch(error=>{console.error(error);process.exitCode=1;});
