const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const creator=fs.readFileSync('js/creator-23.js','utf8'),section=(from,to)=>creator.slice(creator.indexOf(from),creator.indexOf(to,creator.indexOf(from)));
const draws=[],glyphs=[];
function context2d(){return {font:'58px mplantin',clearRect(){},save(){},restore(){},beginPath(){},rect(){},clip(){},fillText(text,x,y){glyphs.push({text,x,y,size:parseFloat(this.font)});},strokeText(){},drawImage(image,x,y){draws.push({image,x,y});},measureText(text){const size=parseFloat(this.font);return {width:String(text).length*size*.45,actualBoundingBoxAscent:size*.65,actualBoundingBoxDescent:0};}};}
const ctx={FontLoadTracker:{track(){}},console,Map,Set,savedFont:null,mana:new Map(),paragraphCanvas:{},lineCanvas:{},paragraphContext:context2d(),lineContext:context2d(),prePTContext:context2d(),navigator:{userAgent:'Chrome'},getManaSymbol(){},card:{width:2010,height:2814,marginX:0,marginY:0,text:{},frames:[]},document:{readyState:'loading',addEventListener(){},querySelector:()=>({checked:false,value:''}),createElement:()=>({getContext:()=>context2d()})},addEventListener(){},drawTextBuffer(){}};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(section('function scaleX(','function normalizeCardOrientation('),ctx);
vm.runInContext(section('var CARD_TEXT_IMPORT_MAX_REDUCTION','function drawTextBuffer('),ctx);
vm.runInContext(section('var justifyWidth =','CanvasRenderingContext2D.prototype'),ctx);
vm.runInContext(fs.readFileSync('js/rulesRange.js','utf8'),ctx);
const fields={cost:{name:'2 - Cost',text:'4:',x:.5093,y:.3,width:.3967,height:.0277,size:.0277},title:{name:'2 - Name',text:'Enter the Gravemind',x:.5093,y:.3,width:.3967,height:.0281,size:.0281,align:'right'}};
ctx.card.text=fields;const range={id:'class-rules-test',kind:'class',bounds:{x:.5093,y:.3,width:.404,height:.3},modules:[{id:'level2',sizing:'flex',size:1,elements:[{kind:'text',key:'cost',offset:{x:0,y:0,width:797.367,height:77.9478},collisionGroup:'class-header',collisionRole:'cost'},{kind:'text',key:'title',offset:{x:0,y:0,width:797.367,height:79.0734},collisionGroup:'class-header',collisionRole:'name'}]}]};ctx.card.rulesRanges=[range];ctx.RulesRange.syncElements();
assert.ok(fields.cost.rangeClip.width<fields.cost.width*.2,'Short costs do not reserve a third of the entire banner');
assert.ok(fields.title.rangeClip.x>=fields.cost.rangeClip.x+fields.cost.rangeClip.width,'Title and cost lanes do not overlap');
const geometry=JSON.stringify({x:fields.title.x,width:fields.title.width});
ctx.writeText(fields.title,context2d());assert.equal(ctx.CardTextFitResults?.length||0,0);const titleDraw=draws.filter(draw=>draw.image===ctx.paragraphCanvas).at(-1);assert.ok(Math.abs(titleDraw.x-(ctx.scaleX(fields.title.rangeClip.x)-300))<.001,'Text origin uses its lane, not the full field');assert.equal(ctx.paragraphCanvas.width,ctx.scaleWidth(fields.title.rangeClip.width)+600);assert.ok(glyphs.some(item=>item.text.includes('Enter')),'The first word is rendered');assert.equal(JSON.stringify({x:fields.title.x,width:fields.title.width}),geometry,'Rendering preserves editable geometry');
// Exercise the actual writer with a long title and a locked range font size.
fields.title.text='A very long level title that needs additional fitting';fields.title.rangeClip.width=.15;fields.title.rangeUniformTextSize=true;glyphs.length=0;ctx.writeText(fields.title,context2d());const fit=ctx.cardTextFitResults.find(item=>item.key==='title');assert.equal(fit.failed,false,'A locked range size does not leave an overflowing title clipped');assert.ok(fit.reduction>0,'The real renderer shrinks a long single-line title to its lane');
if(process.env.CLASS_HEADER_PROJECT_FIXTURE){ctx.card=JSON.parse(fs.readFileSync(process.env.CLASS_HEADER_PROJECT_FIXTURE,'utf8'));ctx.RulesRange.syncElements();for(const key of ['level1b','level2b']){const field=ctx.card.text[key];draws.length=0;ctx.writeText(field,context2d());const result=ctx.cardTextFitResults.find(item=>item.key===key);assert.equal(result.failed,false,'Uploaded Stage title fits: '+field.text);const draw=draws.filter(item=>item.image===ctx.paragraphCanvas).at(-1);assert.ok(Math.abs(draw.x-(ctx.scaleX(field.rangeClip.x)-300))<.001);}console.log('PASS: uploaded Stage template renders both complete level titles inside their cost/title lanes.');}
console.log('PASS: Class header lanes use actual cost width, preserve editable geometry and fit complete titles beside costs.');
