const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createCanvas,Image}=require('@napi-rs/canvas');
const nodes=new Map(),handlers={},events={},messages=[];let commits=0,restores=0;
function node(){return{hidden:false,value:'',checked:false,textContent:'',children:new Map(),querySelector(selector){if(!this.children.has(selector))this.children.set(selector,node());return this.children.get(selector);}};}
const document={readyState:'loading',activeElement:null,querySelector:selector=>nodes.get(selector)||null,createElement(tag){if(tag==='canvas')return createCanvas(1,1);return node();},body:{appendChild(panel){nodes.set('#'+panel.id,panel);}},addEventListener(name,fn){handlers[name]=fn;}};
const range={id:'r',bounds:{x:.15,y:.6,width:.7,height:.3},modules:[{elements:[{kind:'text',key:'rules'}]}]},owner={designLayerId:'rules',name:'Rules',bounds:{...range.bounds},sectionModule:{rangeId:'r'}},type={designLayerId:'type',name:'Type',componentKind:'Type',bounds:{x:.15,y:.5,width:.7,height:.08},masks:[]},pt={designLayerId:'pt',name:'Power/Toughness',bounds:{x:.72,y:.86,width:.12,height:.06},masks:[]};
function asset(frame,color){const c=createCanvas(100,100),ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,100,100);frame.image=c;frame.src=c.toDataURL();frame.opacity=100;}
for(const f of [owner,type,pt])asset(f,'#336699');
const pin={designLayerId:'pin',name:'Pinline',bounds:{x:0,y:0,width:1,height:1},masks:[]};asset(pin,'#ffcc00');
const card={width:1000,height:1000,frames:[pt,type,owner,pin],rulesRanges:[range],text:{type:{x:.2,y:.52,width:.5,height:.04,size:.05,text:'Creature'},rules:{...range.bounds,text:'Long rules'},pt:{x:.74,y:.875,width:.08,height:.03}}};
const context={document,Image,console,setTimeout,clearTimeout,card,activeFrameDesignMode:'frames',previewCanvas:{style:{},addEventListener(name,fn){events[name]=fn;}},previewContext:createCanvas(1000,1000).getContext('2d'),window:null,RulesRange:{getSelected:()=>card.rulesRanges[0],refresh(){}},FrameSectionTools:{originalRectangle:async frame=>({...frame.bounds}),cutouts(){},syncRuleModules(){}},FrameTextPresets:{sync(){}},CanvasDesignTools:{suspend(){},resume(){}},drawCard(){},drawFrames(){},drawTextBuffer(){},previewLayoutBounds:b=>({x:b.x*1000,y:b.y*1000,width:b.width*1000,height:b.height*1000}),setFrameDesignMode(mode){context.activeFrameDesignMode=mode;},notify:message=>messages.push(message),createDesignStateSnapshot:()=>({}),applyDesignStateSnapshot:async()=>{restores++;},rebuildFrameLayerList:async()=>{},ensureDesignLayerId:frame=>frame.designLayerId ||= 'piece-'+card.frames.length,commitDesignUndoSnapshot(){commits++;},drawFrameLayerImage:(ctx,img,x,y,w,h)=>ctx.drawImage(img,x,y,w,h),drawFrameLayerMask:(ctx,img,x,y,w,h)=>ctx.drawImage(img,x,y,w,h),addEventListener(){}};context.window=context;
vm.createContext(context);vm.runInContext(fs.readFileSync('js/containerResizeTools.js','utf8'),context);const T=context.ContainerResizeTools;
let b={x:.2,y:.3,width:.4,height:.3};let mirror=T.resized(b,'lefttop',-.05,-.05,true,1000,1000);assert.ok(Math.abs(mirror.x+mirror.width/2-.4)<1e-9);assert.ok(Math.abs(mirror.y+mirror.height/2-.45)<1e-9);assert.equal(mirror.width,.5);assert.equal(mirror.height,.4);
let single=T.resized(b,'right',.1,0,false,1000,1000);assert.equal(single.x,.2);assert.equal(single.y,.3);assert.equal(single.height,.3);
const source=createCanvas(100,100);source.getContext('2d').fillStyle='#f00';source.getContext('2d').fillRect(0,0,8,8);const resized=T.slices(source,200,150);assert.equal(resized.getContext('2d').getImageData(7,7,1,1).data[3],255);assert.equal(resized.getContext('2d').getImageData(12,12,1,1).data[3],0,'Corner thickness stays unchanged');
(async()=>{
 assert.equal(T.cursor('left'),'ew-resize');assert.equal(T.cursor('top'),'ns-resize');assert.equal(T.cursor('lefttop'),'nwse-resize');assert.equal(T.cursor('righttop'),'nesw-resize');
 let textPreviews=0;context.drawText=async()=>{textPreviews++;card.text.rules.rangeFontReduction=Math.max(0,Math.round(200/card.rulesRanges[0].bounds.width));};
 const initial=JSON.stringify(card,(key,value)=>key==='image'?undefined:value);
 await T.open();assert.equal(T.isOpen(),true);const panel=nodes.get('#container-resize-editor');panel.querySelector('[data-width]').value=850;panel.querySelector('[data-width]').onchange({target:{value:'850'}});
 await T.flushPreview();assert.ok(owner.bounds.width>.7,'Frame geometry changes during preview');assert.ok(textPreviews>0,'Live preview runs the text fitter');assert.equal(commits,0,'Preview does not create history');const firstReduction=card.text.rules.rangeFontReduction;panel.querySelector('[data-width]').onchange({target:{value:'950'}});await T.flushPreview();assert.ok(card.text.rules.rangeFontReduction<firstReduction,'Wider live preview recalculates the fitted font');assert.equal(card.frames.length,5,'Repeated previews rebuild from the baseline rather than accumulating pieces');await T.cancel();assert.equal(T.isOpen(),false);delete card.text.rules.rangeFontReduction;assert.deepEqual(JSON.parse(JSON.stringify(card,(key,value)=>key==='image'?undefined:value)),JSON.parse(initial),'Cancel leaves the complete layout untouched');assert.equal(context.activeFrameDesignMode,'frames');assert.equal(commits,0);
 await T.open();panel.querySelector('[data-width]').onchange({target:{value:'850'}});panel.querySelector('[data-height]').onchange({target:{value:'480'}});await panel.querySelector('[data-confirm]').onclick();
 assert.equal(messages.length,0);assert.equal(restores,0);assert.equal(commits,1,'Confirm is one undoable edit');assert.equal(T.isOpen(),false);assert.equal(context.activeFrameDesignMode,'frames');assert.ok(owner.bounds.width>.7);assert.equal(pt.bounds.width,.12,'Badge size preserved');assert.equal(type.bounds.height,.08,'Type-line height preserved');assert.equal(owner.resizeContainer.pinlineIds.length,1);assert.equal(pin.bounds.width,1,'Other pinline regions retain their geometry');assert.ok(card.frames.find(frame=>frame.name.includes('Rules container')));assert.equal(card.text.type.size,.05,'Text default font is preserved');
 const metadata=JSON.parse(JSON.stringify(owner.resizeContainer));assert.equal(metadata.pinlineIds.length,1,'Container membership survives project serialization');context.activeFrameDesignMode='fields';await T.open();await T.cancel();assert.equal(context.activeFrameDesignMode,'fields','Layout field view is restored as well');
 console.log('PASS: live frame/text preview, resize cursors, no preview history, cancellation, atomic confirmation and preserved type/P/T geometry.');
})().catch(error=>{console.error(error);process.exitCode=1;});
