const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const clone=value=>JSON.parse(JSON.stringify(value));
const source=process.env.EMBARK_PROJECT_FIXTURE?JSON.parse(fs.readFileSync(process.env.EMBARK_PROJECT_FIXTURE,'utf8')):{version:'dungeonModules',width:2010,height:2814,text:{title:{text:'Keep'}},frames:[{name:'Custom pipeline'}],dungeonModules:[],dungeonPadding:12,dungeonVerticalPadding:{top:8,bottom:9}};
if(!source.dungeonModules.length)for(let row=0;row<5;row++)for(let col=0;col<(row===2?2:1);col++){const id='r'+row+'c'+col;source.dungeonModules.push({id,textKey:id,name:id,bounds:{x:row===4?.07:.51+col*.21,y:.11+row*.14,width:row===4?.86:row===2?.21:.42,height:.14}});source.text[id]={name:id,text:'Old',font:'belerenb',size:.0324,align:'center'};}
const ctx={console,card:clone(source),RulesRange:{measureModuleText:(text,width,reduction)=>Math.max(1,Math.ceil(text.text.length*30/width))*(60-reduction)},document:{querySelector:()=>null}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('js/dungeonModules.js','utf8'),ctx);const D=ctx.DungeonModules;
const fields={dungeonRooms:'1;2|3;4|5;6|7;8'};for(let n=1;n<=12;n++)fields['ability'+n]='  Ability '+n+'  ';
const data=clone(source),original=JSON.stringify(source);assert.equal(D.applyCsvRooms(data,fields,[]),true);assert.equal(data.dungeonModules.length,8);assert.equal(JSON.stringify(source),original);
for(const room of data.dungeonModules){assert.equal(data.text[room.textKey].font,'mplantin');assert.equal(data.text[room.textKey].text,'Ability '+room.csvAbility);assert.ok(data.text[room.textKey].width<room.bounds.width);}
for(let i=1;i<=3;i++){const rooms=data.dungeonModules.filter(r=>r.csvRowId===source.dungeonModules.filter((r,j,all)=>!j||Math.abs(r.bounds.y-all[j-1].bounds.y)>.001)[i].id);assert.equal(rooms.length,2);assert.equal(rooms[0].bounds.width,rooms[1].bounds.width);assert.equal(rooms[0].bounds.y,rooms[1].bounds.y);assert.equal(rooms[0].bounds.height,rooms[1].bounds.height);}
assert.deepEqual(data.frames,source.frames);assert.ok(Math.abs(data.dungeonModules.at(-1).bounds.width-source.dungeonModules.at(-1).bounds.width)<1e-12,'Wide bottom room preserved');
const ids=data.dungeonModules.map(r=>r.id);D.applyCsvRooms(data,fields,[]);assert.deepEqual(data.dungeonModules.map(r=>r.id),ids,'Repeat preview retains stable room IDs');
assert.ok(data.artBounds.x>=source.dungeonModules.at(-1).bounds.x);
assert.ok(data.artBounds.x+data.artBounds.width<=source.dungeonModules[0].bounds.x);
assert.ok(data.artBounds.y+data.artBounds.height<source.dungeonModules.at(-1).bounds.y);
const explicitArt=clone(source);explicitArt.artBounds={x:.1,y:.2,width:.3,height:.4};D.applyCsvRooms(explicitArt,fields,[]);assert.deepEqual(explicitArt.artBounds,{x:.1,y:.2,width:.3,height:.4},'Explicit art bounds preserved');
const copy=clone(source),before=JSON.stringify(copy);assert.throws(()=>D.applyCsvRooms(copy,{dungeonRooms:'1|2;3;4;5;6'},[]),/Only dungeon rows/);assert.equal(JSON.stringify(copy),before);assert.throws(()=>D.applyCsvRooms(copy,{dungeonRooms:'1;2'},[]),/requires 5 rows/);assert.throws(()=>D.applyCsvRooms(copy,{dungeonRooms:'1;2;0;3;4'},[]),/1 to 12/);
const warnings=[];D.applyCsvRooms(clone(source),{dungeonRooms:'1;2;3;4;5'},warnings);assert.equal(warnings.length,5);
D.applyCsvRooms(data,{...fields,dungeonRooms:'1;2;3;4;5'},[]);assert.equal(data.dungeonModules.length,5);assert.equal(Object.keys(data.text).filter(k=>k.endsWith('Right')).length,0,'Merged rooms remove their generated text fields');
const fitted=clone(source);D.applyCsvRooms(fitted,fields,[]);ctx.card=fitted;fitted.dungeonAutoFit=true;fitted.dungeonHeightLock={top:fitted.dungeonModules[0].bounds.y,bottom:fitted.dungeonModules.at(-1).bounds.y+fitted.dungeonModules.at(-1).bounds.height};D.reflow();
for(const row of new Set(fitted.dungeonModules.map(r=>r.csvRowId))){const pair=fitted.dungeonModules.filter(r=>r.csvRowId===row);if(pair.length===2){assert.equal(pair[0].bounds.y,pair[1].bounds.y);assert.equal(pair[0].bounds.height,pair[1].bounds.height);}}
const pair=fitted.dungeonModules.filter(r=>r.csvRowId===fitted.dungeonModules[1].csvRowId);pair[0].bounds.height+=.02;D.snapRoom(pair[0],'bottom');assert.equal(pair[0].bounds.height,pair[1].bounds.height,'Manual edge dragging keeps paired row heights equal');
console.log('PASS: dungeon CSV assignments, optional equal splits, stable IDs, cleanup, Plantin, geometry preservation, paired autofit and dragging.');
