const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {createCanvas,Image}=require('@napi-rs/canvas');
const context={console,Image,window:null,addEventListener(){},document:{readyState:'loading',addEventListener(){},querySelector(){return null;},createElement:()=>createCanvas(1,1)}};context.window=context;vm.createContext(context);
for(const file of ['templateThemes','containerResizeTools'])vm.runInContext(fs.readFileSync('js/'+file+'.js','utf8'),context);
const T=context.ContainerResizeTools;
function art(lines,color='black',half=false){const c=createCanvas(100,100),ctx=c.getContext('2d');ctx.fillStyle=color;for(const [y,h] of lines)ctx.fillRect(half?50:0,y,half?50:100,h);return c;}
function reference(half=false){const c=createCanvas(100,60),ctx=c.getContext('2d');ctx.drawImage(art([[0,3],[15,6],[50,6]],half?'green':'black',half),0,0);return c.toDataURL();}
const bounds={x:0,y:.43,width:1,height:.6};
const data={width:100,height:100,text:{type:{x:.1,y:.45,width:.7,height:.1,text:'Boss'},rules:{text:'Keep'},prototype:{text:'Loot'}},rulesRanges:[],templateThemes:{families:[{id:'p',variants:{b:{src:art([[5,3],[40,6],[55,6],[90,6]]).toDataURL()},g:{src:art([[5,3],[40,6],[55,6],[90,6]],'green').toDataURL()}}}]},frames:[{name:'Rules',designLayerId:'owner',resizeContainer:{bounds:{...bounds},pinlineIds:['pipe','half'],typeIds:['type']},bounds:{x:.1,y:.6,width:.8,height:.3}},{name:'Black Pipeline Complete — Rules container',designLayerId:'pipe',src:reference(),bounds:{...bounds},templateTheme:{familyId:'p',side:'full',sourceRegion:{x:0,y:.43,width:1,height:.53}},resizeContainerRaster:true},{name:'Green Pipeline Completed — Right Half — Rules container',designLayerId:'half',src:reference(true),bounds:{...bounds},resizeContainerRaster:true},{name:'Black Pipeline Complete',src:art([[40,3]]).toDataURL(),bounds:{x:0,y:0,width:1,height:1},resizeContainerRaster:true},{name:'Green Pipeline Completed — Right Half',src:art([[40,3]],'green',true).toDataURL(),bounds:{x:0,y:0,width:1,height:1},resizeContainerRaster:true},{name:'Type',designLayerId:'type',bounds:{x:.07,y:.45,width:.84,height:.12}}]};
(async()=>{
 const text=data.text.type.text,range=JSON.stringify(data.rulesRanges);assert.equal(await T.migrate(data),true);assert.equal(data.frames[1].pipelineRepairVersion,1);assert.equal(data.frames[1].bounds.y,.4);assert.equal(data.frames[2].bounds.y,.4,'Half overlay moves with the repaired pipeline');assert.equal(data.frames[2].hidden,undefined,'Opening preserves saved split appearance');assert.equal(data.frames[3].hidden,true);assert.equal(data.frames[4].hidden,true,'Both old full-frame remnants are cleared');assert.ok(Math.abs(data.frames[5].bounds.x+data.frames[5].bounds.width/2-.5)<1e-8,'Type artwork is horizontally centered on the pipeline');assert.ok(Math.abs(data.frames[5].bounds.y+data.frames[5].bounds.height/2-.52)<1e-8,'Type artwork is vertically centered between the restored strokes');assert.equal(data.text.type.text,text);assert.equal(JSON.stringify(data.rulesRanges),range);const once=JSON.stringify(data);assert.equal(await T.migrate(data),false);assert.equal(JSON.stringify(data),once,'Migration is idempotent');
 if(process.env.CONTAINER_PROJECT_FIXTURE){const card=JSON.parse(fs.readFileSync(process.env.CONTAINER_PROJECT_FIXTURE));const before=JSON.stringify(card.text),ruleText=card.text.rules.text,prototypeKey=Object.keys(card.text).find(key=>key.startsWith('prototype-')),geometry=JSON.stringify(card.rulesRanges);await T.migrate(card);assert.equal(card.frames[12].pipelineRepairVersion,1);assert.equal(card.frames[8].hidden,true);assert.equal(card.frames[14].hidden,true);assert.equal(card.text.rules.text,ruleText);assert.equal(card.text[prototypeKey].text,JSON.parse(before)[prototypeKey].text);assert.equal(JSON.stringify(card.rulesRanges),geometry);const saved=JSON.stringify(card);await T.migrate(card);assert.equal(JSON.stringify(card),saved);console.log('PASS: actual older Boss project migrates once without changing its rules, prototype text or range.');}
 const creator=fs.readFileSync('js/creator-23.js','utf8'),load=creator.slice(creator.indexOf('async function loadCardData('),creator.indexOf('async function loadCard(selectedCardKey)'));
 assert.ok(load.indexOf('await window.ContainerResizeTools?.migrate(card)')<load.indexOf('const framesInLoadOrder'),'Migration runs before rendering frames');assert.ok(load.includes('await drawText();'),'Load awaits fitting even when dimensions are unchanged');
 const node={value:'',innerHTML:'',checked:false,classList:{remove(){}}};let fitted=0,migrated=0,loaded=0;
 const loadContext={console,window:null,document:{querySelector:()=>node,getElementById:()=>node},selectedTextIndex:0,selectedFrame:null,date:new Date(),writingText:null,canvasList:[],clearTimeout(){},clearDesignUndoHistory(){},currentCardOrientation:()=> 'portrait',syncCardOrientationState(){},artistEdited(){},scaleX:n=>n,scaleY:n=>n,scaleWidth:n=>n,scaleHeight:n=>n,loadTextOptions(){},uploadArt(){},uploadSetSymbol:async()=>{},uploadWatermark(){},serialInfoEdited(){},addFrame:async()=>{loaded++;},drawFrames(){},bottomInfoEdited(){},watermarkEdited(){},drawText:async()=>{fitted++;},ContainerResizeTools:{migrate:async()=>{migrated++;}},TemplateThemes:{refresh(){}},notify(){}};loadContext.window=loadContext;vm.createContext(loadContext);vm.runInContext(load,loadContext);await loadContext.loadCardData({width:100,height:100,frames:[{name:'Frame'}],text:{rules:{text:'Example'}}});assert.equal(migrated,1);assert.equal(loaded,1);assert.equal(fitted,1,'An unchanged canvas size still awaits a fresh text fit');
 console.log('PASS: complete stroke migration, both saved color halves, type-line centering, content preservation and repeat loads.');
})().catch(error=>{console.error(error);process.exitCode=1;});
