const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const creator=fs.readFileSync('js/creator-23.js','utf8'),section=(from,to)=>creator.slice(creator.indexOf(from),creator.indexOf(to,creator.indexOf(from)));
let metricFactor=.45;
function context2d(){return {font:'58px mplantin',clearRect(){},save(){},restore(){},beginPath(){},rect(){},clip(){},fillText(){},strokeText(){},drawImage(){},measureText(text){const size=parseFloat(this.font);return {width:String(text).length*size*metricFactor,actualBoundingBoxAscent:size*.65,actualBoundingBoxDescent:size*.1};}};}
const ctx={console,Map,Set,savedFont:null,mana:new Map(),FontLoadTracker:{track(){}},paragraphCanvas:{},lineCanvas:{},paragraphContext:context2d(),lineContext:context2d(),prePTContext:context2d(),navigator:{userAgent:'Chrome'},getManaSymbol(){},card:{width:2814,height:2010,marginX:0,marginY:0,text:{},frames:[]},document:{querySelector:()=>({checked:false,value:''})}};ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(section('function scaleX(','function normalizeCardOrientation('),ctx);
vm.runInContext(section('var CARD_TEXT_IMPORT_MAX_REDUCTION','function drawTextBuffer('),ctx);
vm.runInContext(section('var justifyWidth =','CanvasRenderingContext2D.prototype'),ctx);
const field={name:'Prototype Rules',csvFieldLabel:'Loot Box',sectionField:'prototype',text:'Search your library for an artifact card, a creature card, and a land card. Put them onto the battlefield tapped.',x:.1,y:.75,width:.8,height:.18,size:.0295};
ctx.card.text['prototype-layer-random']=field;
const badge={name:'Multicolored Power/Toughness',bounds:{x:.78,y:.83,width:.14,height:.1},opacity:100};ctx.card.frames=[badge];
for(const data of [field,{...field,sectionField:undefined},{name:'Renamed text',standardRole:'rules'},{name:'Rules',csvFieldLabel:'custom',sectionField:'prototype'}])assert.equal(ctx.cardTextSemanticRole(data,'random-id'),'rules','Custom labels and generated IDs retain rules semantics');
assert.equal(ctx.cardTextSemanticRole({name:'Prototype Mana Cost',manaCost:true}),'mana');assert.equal(ctx.cardTextSemanticRole({name:'Prototype Power/Toughness'},'pt2'),'pt');
const fit=ctx.getCardTextCollisionFit(field,ctx.scaleWidth(field.width),ctx.scaleHeight(field.height));assert.equal(fit.regions.length,1);assert.deepEqual(Array.from(fit.obstacles),['Power/Toughness Box']);
const obstacle=fit.regions[0],full=ctx.scaleWidth(field.width),above=ctx.cardTextLineAvailableWidth(fit.regions,0,30,full,0),beside=ctx.cardTextLineAvailableWidth(fit.regions,obstacle.top+1,30,full,0);assert.equal(above,full,'Lines above the badge retain full width');assert.ok(beside<full,'Only lines beside the visible P/T asset are shortened');
ctx.writeText(field,context2d());let rendered=ctx.cardTextFitResults.find(item=>item.key==='prototype-layer-random');assert.equal(rendered.failed,false,'Actual renderer fits the prototype text safely');assert.ok(rendered.obstacles.includes('Power/Toughness Box'));
// The frame asset remains the obstacle even without a P/T text field.
assert.equal(Object.keys(ctx.card.text).length,1);badge.bounds.x=.7;const moved=ctx.getCardTextCollisionFit(field,full,ctx.scaleHeight(field.height));assert.ok(moved.regions[0].left<obstacle.left,'Wrapping follows the moved badge');badge.hidden=true;assert.equal(ctx.getCardTextCollisionFit(field,full,ctx.scaleHeight(field.height)).regions.length,0,'Hidden badges do not reserve space');
// Main rules use the same line-by-line wrapping around the attached Loot Box tag.
const main={name:'Rules Text',text:'Main ability text near its tag',x:.1,y:.6,width:.8,height:.25,size:.0295};ctx.card.text.rules=main;
const tag={name:'Module tag',designLayerId:'tag',bounds:{x:.75,y:.78,width:.15,height:.08},opacity:100};ctx.card.frames=[{designLayerId:'owner',sectionModule:{mainKey:'rules',rangeId:'tag-range'}},tag];ctx.card.rulesRanges=[{id:'tag-range',modules:[{elements:[{kind:'frame',key:'tag',anchor:{x:'right',y:'top'}}]}]}];
const tagFit=ctx.getCardTextCollisionFit(main,ctx.scaleWidth(main.width),ctx.scaleHeight(main.height));assert.deepEqual(Array.from(tagFit.obstacles),['Loot Box']);assert.equal(tagFit.regions.length,1);assert.equal(ctx.cardTextLineAvailableWidth(tagFit.regions,0,30,ctx.scaleWidth(main.width),0),ctx.scaleWidth(main.width));assert.ok(ctx.cardTextLineAvailableWidth(tagFit.regions,tagFit.regions[0].top+1,30,ctx.scaleWidth(main.width),0)<ctx.scaleWidth(main.width));assert.equal(ctx.getCardTextCollisionFit(field,full,ctx.scaleHeight(field.height)).obstacles.includes('Loot Box'),false,'Tag wrapping applies to its main rules field only');tag.hidden=true;assert.equal(ctx.getCardTextCollisionFit(main,ctx.scaleWidth(main.width),ctx.scaleHeight(main.height)).regions.length,0);tag.hidden=false;tag.bounds.y=.9;assert.equal(ctx.getCardTextCollisionFit(main,ctx.scaleWidth(main.width),ctx.scaleHeight(main.height)).regions.length,0,'Tag movement updates the reserved area');
console.log('PASS: Boss Prototype/Loot Box fields wrap around visible P/T assets with generated keys, renamed labels and moved badges.');

// Re-run shared sizing when the real font replaces its narrower fallback metrics.
Object.assign(ctx.document,{readyState:'loading',addEventListener(){}});ctx.addEventListener=()=>{};ctx.FrameTextPresets={remap(r,f,t){r.x=t.x+(r.x-f.x)*t.width/f.width;r.y=t.y+(r.y-f.y)*t.height/f.height;r.width*=t.width/f.width;r.height*=t.height/f.height;}};ctx.redrawFrames=false;
const base={x:.1,y:.5,width:.8,height:.4,rotation:0},partBox={x:.1,y:.78,width:.8,height:.12,rotation:0},protoKey='prototype-part';
ctx.card={width:1000,height:1000,marginX:0,marginY:0,text:{rules:{name:'Rules Text',text:'Main ability',x:.12,y:.51,width:.76,height:.26,size:.1},[protoKey]:{name:'Prototype Rules',sectionField:'prototype',text:'Draw three cards. You get an emblem with "Once on each of your turns you may cast a spell without paying its mana cost."',x:.12,y:.79,width:.76,height:.1,size:.1}},frames:[{designLayerId:'owner',bounds:{...base},sectionModule:{rangeId:'range',partId:'part',mainKey:'rules',baseBounds:{...base},lastOwnerBounds:{...base},lastPartBounds:{...partBox},mainRelative:{x:.025,y:.025,width:.95,height:.95},fraction:.3,position:'bottom',rulesFontVersion:1}},{designLayerId:'part',bounds:{...partBox}}],rulesRanges:[{id:'range',bounds:{...base},uniformTextSize:true,autoSizeModules:true,modules:[{id:'main',elements:[{kind:'text',key:'rules'}]},{id:'proto',size:120,maxSize:150,elements:[{kind:'frame',key:'part',relative:{x:0,y:0,width:1,height:1}},{kind:'text',key:protoKey,relative:{x:.025,y:1/12,width:.95,height:5/6}}]}]}]};
vm.runInContext(fs.readFileSync('js/frameSectionTools.js','utf8'),ctx);
(async()=>{const fits=async(field,key)=>{ctx.resetCardTextFitState();ctx.writeText(field,context2d());return !ctx.cardTextFitResults.find(f=>f.key===key)?.failed;};metricFactor=.04;await ctx.FrameSectionTools.fitUniformText(fits);const first=ctx.card.frames[0].sectionModule.uniformSize;metricFactor=.45;await ctx.FrameSectionTools.fitUniformText(fits);const actual=ctx.card.frames[0].sectionModule.uniformSize;assert.ok(actual<first,'Actual font metrics invalidate the previous fit');assert.equal(ctx.card.rulesRanges[0].fitOverflow,false);for(const key of ['rules',protoKey])assert.equal(await fits(ctx.card.text[key],key),true,'Entire text fits after the cache is revalidated');assert.equal(ctx.card.text[protoKey].clipToBounds,true);console.log('PASS: actual renderer refits cached Prototype text after font metrics change without cropping its last line.');})().catch(error=>{console.error(error);process.exitCode=1;});
