const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createCanvas,Image}=require('@napi-rs/canvas');
const document={readyState:'loading',addEventListener(){},querySelector(){return null;},createElement(tag){assert.equal(tag,'canvas');return createCanvas(1,1);}};
const mask=createCanvas(100,100),maskctx=mask.getContext('2d');for(let x=0;x<100;x++){maskctx.fillStyle=`rgba(0,0,0,${x/99})`;maskctx.fillRect(x,0,1,100);}
const context={document,Image,console,window:null,addEventListener(){},fixUri:src=>src==='/img/frames/maskRightHalf.png'?mask.toDataURL():/^\/img\/.*(?:m15PT|\/pt)[A-Z]\.png$/.test(src)?asset(src.includes('U.png')?'blue':'gold').src:src};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('js/templateThemes.js','utf8'),context);const T=context.TemplateThemes;
const clone=value=>JSON.parse(JSON.stringify(value));
function asset(color,alpha=1){const canvas=createCanvas(100,100),ctx=canvas.getContext('2d');ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.fillRect(0,0,100,100);return {src:canvas.toDataURL()};}
const source={width:2814,height:2010,artBounds:{x:.1,y:.2,width:.8,height:.3},text:{random:{name:'Prototype Rules',text:'Old',x:.1,size:.03}},rulesRanges:[{bounds:{x:.1,y:.5,width:.8,height:.4}}],templateThemes:{enabled:true,families:[{id:'pin',name:'Pinline',variants:{w:asset('white'),u:asset('blue'),b:asset('black'),r:asset('red',.5),g:asset('green',.5),c:asset('gray'),m:asset('gold')}}]},frames:[{name:'Pinline',src:'original',bounds:{x:0,y:0,width:1,height:1},opacity:70,templateTheme:{familyId:'pin',side:'full',masks:[]}}, {name:'Fixed',src:'fixed',bounds:{x:.2,y:.2,width:.1,height:.1}}]};
async function pixel(src,x,y){const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=src;});const c=createCanvas(100,100);c.getContext('2d').drawImage(img,0,0,100,100);return [...c.getContext('2d').getImageData(x,y,1,1).data];}
(async()=>{
 assert.equal(T.selection({color:'unknown',frameLeftColor:'U'}).left,'u','Explicit color takes precedence');assert.equal(T.selection({color:'WUBRG'}).left,'m');assert.equal(T.selection({color:'Colorless'}).left,'c');assert.equal(T.selection({colorIdentity:'Blue Black'}).right,'b');assert.throws(()=>T.selection({frameLeftColor:'WU'}),/one color/);assert.throws(()=>T.selection({frameRightColor:'G'}),/requires/);assert.throws(()=>T.colors('purple'),/Unknown/);
 for(const color of ['W','U','B','R','G','C','M','WU','UB','BR','RG','GW','WB','UR','BG','RW','GU']){const data=clone(source);await T.apply(data,{color});assert.deepEqual(data.frames[0].bounds,source.frames[0].bounds);assert.deepEqual(data.artBounds,source.artBounds);assert.deepEqual(data.rulesRanges,source.rulesRanges);assert.deepEqual(data.text,source.text);assert.equal(data.frames[1].src,'fixed');assert.equal(data.frames[0].opacity,70);}
 const pairChoice=T.selection({color:'BG'});
 for(const name of ['Title','Type','Power/Toughness','Prototype box'])assert.equal(T.elementChoice({name},source,pairChoice).left,'m',name+' uses gold');
 for(const frame of [{name:'Rules Text'},{name:'Black Pipeline'},{name:'Legendary crown'}]){const recipe=frame.name==='Native'?{kind:'native'}:null;assert.equal(T.elementChoice(frame,source,pairChoice,recipe).right,'g','Rules, pipeline and crown split');}
 for(const frame of [{name:'Blue Frame',componentKind:'Frame'},{name:'Native',masks:[]}])assert.equal(T.elementChoice(frame,source,pairChoice,{kind:'native'}).left,'m','Frame bodies use gold');
 assert.equal(T.selection({color:'Multicolor',colorIdentity:'BG'}).right,'g','Identity supplies the colors rather than the multicolor bucket');
 const artifactData={text:{type:{text:'Legendary Artifact Creature'}}};
 for(const identity of ['U','BG']){const choice=T.selection({colorIdentity:identity});assert.equal(T.elementChoice({componentKind:'Frame'},artifactData,choice).left,'a');assert.equal(T.elementChoice({componentKind:'Title'},artifactData,choice).left,identity==='U'?'u':'m');assert.equal(T.elementChoice({componentKind:'Rules'},artifactData,choice).left,identity==='U'?'u':'b');}
 const rulesAndPrototype=clone(source);rulesAndPrototype.frames=[{...clone(source.frames[0]),name:'Rules background',componentKind:'Rules'},{...clone(source.frames[0]),name:'Prototype box'}];await T.apply(rulesAndPrototype,{color:'BG'});assert.ok((await pixel(rulesAndPrototype.frames[0].src,99,50))[1]>120,'Rules background uses its green half');assert.deepEqual(await pixel(rulesAndPrototype.frames[1].src,50,50),[255,215,0,255],'Prototype stays gold on a dual-color card');
 const linkedTitle=clone(source);linkedTitle.frames[0].name='Custom Title';await T.apply(linkedTitle,{color:'BG'});assert.deepEqual(await pixel(linkedTitle.frames[0].src,50,50),[255,215,0,255],'Explicitly linked title uses the gold family variant');
 const split=clone(source);await T.apply(split,{frameLeftColor:'R',frameRightColor:'G'});const mid=await pixel(split.frames[0].src,50,50);assert.ok(mid[3]>=125&&mid[3]<=130,'Complementary split blending preserves translucent alpha');assert.ok(mid[0]>100&&mid[1]>45,'Both colors contribute at the seam');
 const right=clone(source);right.frames[0].bounds={x:.75,y:0,width:.25,height:1};await T.apply(right,{color:'WU'});const edge=await pixel(right.frames[0].src,0,50);assert.ok(edge[2]>180,'Blend follows card coordinates instead of restarting at each layer');
 const missing=clone(source);missing.frames.push({name:'Missing',templateTheme:{familyId:'other'},src:'stay'});const before=JSON.stringify(missing);await assert.rejects(T.apply(missing,{color:'W'}),/Missing asset family/);assert.equal(JSON.stringify(missing),before,'A failing layer leaves the entire template unchanged');
 const absent=clone(source);await assert.rejects(T.apply(absent,{color:'Artifact'}),/missing Artifact/);assert.equal(absent.frames[0].src,'original');await T.apply(absent,{});assert.equal(absent.frames[0].src,'original','Blank color retains the saved appearance');
 const disabled=clone(source);disabled.templateThemes.enabled=false;disabled.templateThemes.autoStock=false;await T.apply(disabled,{color:'purple'});assert.equal(disabled.frames[0].src,'original');
 const fields=clone(source),warnings=[];T.mapFields(fields,{'prototype rules':['New rules']},warnings);assert.equal(fields.text.random.text,'New rules');fields.text.second={name:'Prototype Rules',text:'Keep'};T.mapFields(fields,{'prototype rules':['Ambiguous']},warnings);assert.equal(fields.text.random.text,'New rules');assert.match(warnings[0],/ambiguous/);
 fields.frames[0].templateTheme.masks=[{src:'data:mask'}];assert.equal(T.records(fields).length,8,'Project records include every variant and linked mask');T.restore(fields.frames[0],{src:fields.frames[0].src});assert.equal(fields.frames[0].templateTheme,undefined,'Undo removes newly added links');
 const paired=clone(source);paired.frames[0].name='Black Battle Pipeline Complete — Rules container';paired.frames[0].designLayerId='left-pipeline';paired.frames[0].templateTheme.sourceRegion={x:.1,y:.5,width:.8,height:.5};paired.frames[0].bounds={x:.1,y:.5,width:.8,height:.5};
 const duplicate={name:'Green Battle Pipeline Completed — Right Half — Rules container',designLayerId:'right-pipeline',bounds:clone(paired.frames[0].bounds),src:'original-right',templateTheme:{familyId:'pin',side:'right',masks:[]}};paired.frames.unshift(duplicate);paired.frames.push({name:'Green Battle Pipeline Completed — Right Half — Title container',bounds:{x:.1,y:.1,width:.8,height:.1},src:'keep-title'}, {name:'Unrelated Right Half',bounds:clone(duplicate.bounds),src:'keep-other'});
 const savedPair=JSON.stringify(paired);await T.apply(paired,{color:'WU'});assert.equal(duplicate.hidden,true,'Matching duplicate half is suppressed in generated output');assert.equal(duplicate.src,'original-right','The malformed duplicate link is not rendered');assert.equal(paired.frames[1].hidden,undefined,'The full blended owner remains visible');assert.equal(paired.frames[3].hidden,undefined,'Different regions remain untouched');assert.equal(paired.frames[4].hidden,undefined,'Unrelated aligned layers remain untouched');assert.equal(paired.frames.length,5,'No frame or module reference is deleted');
 const oneColor=JSON.parse(savedPair);await T.apply(oneColor,{color:'U'});assert.equal(oneColor.frames[0].hidden,true,'Single-color generation also suppresses the old half');
 const failingPair=JSON.parse(savedPair),originalPair=JSON.stringify(failingPair);await assert.rejects(T.apply(failingPair,{color:'Artifact'}),/missing Artifact/);assert.equal(JSON.stringify(failingPair),originalPair,'Suppression waits until all artwork succeeds');
 const different=JSON.parse(savedPair);different.frames[0].templateTheme.familyId='other-family';assert.equal(T.pipelineDuplicates(different).size,0,'Distinct explicitly linked families are not merged');
 // Resized pipeline geometry must survive replacing its color artwork.
 const pipeline=(color,left,top,right,divider,bottom)=>{const c=createCanvas(100,100),ctx=c.getContext('2d');ctx.fillStyle=color;ctx.fillRect(left,top,right-left,3);ctx.fillRect(left,divider,right-left,3);ctx.fillRect(left,bottom,right-left,3);ctx.fillRect(left,top,3,bottom-top);ctx.fillRect(right-3,top,3,bottom-top);return c;};
 const reference=pipeline('black',0,0,100,20,90),original=pipeline('blue',8,8,92,35,90);
 const soft=pipeline('rgba(0,0,0,.5)',0,0,100,20,90),paint=pipeline('rgba(0,0,255,.5)',8,8,92,35,90),retinted=T.fitPipeline(paint,soft);assert.equal(retinted.getContext('2d').getImageData(50,21,1,1).data[3],soft.getContext('2d').getImageData(50,21,1,1).data[3],'Color switching preserves edge coverage without multiplying alpha');
 const resized=clone(source);resized.width=resized.height=100;resized.frames=[{name:'Battle Pipeline — Rules container',src:reference.toDataURL(),resizeContainerRaster:true,bounds:{x:0,y:0,width:1,height:1},templateTheme:{familyId:'pin',side:'full',masks:[]}}];resized.templateThemes.families[0].variants.u={src:original.toDataURL()};resized.templateThemes.families[0].variants.w={src:pipeline('white',8,8,92,35,90).toDataURL()};
 for(const color of ['U','WU']){const card=clone(resized);await T.apply(card,{color});assert.ok((await pixel(card.frames[0].src,50,21))[3]>240,'Divider uses saved expanded location');assert.equal((await pixel(card.frames[0].src,50,36))[3],0,'Default divider does not reappear');assert.ok((await pixel(card.frames[0].src,1,60))[3]>240,'Outer edge uses saved width');assert.deepEqual(card.frames[0].bounds,resized.frames[0].bounds);}
 // Stock elements work without enabling custom families or uploading stock assets.
 const stock={width:100,height:100,text:{type:{text:'Creature'},rules:{text:'Keep'}},frames:[{designLayerId:'pt',name:'Power/Toughness',src:'/img/frames/m15/regular/m15PTM.png',bounds:{x:.7,y:.8,width:.2,height:.1},rotation:15,opacity:60,masks:[]}],rulesRanges:[]};
 await T.apply(stock,{colorIdentity:'U'});assert.equal(stock.frames[0].src,'/img/frames/m15/regular/m15PTU.png');assert.equal(stock.frames[0].rotation,15);assert.equal(stock.frames[0].opacity,60);assert.equal(stock.text.rules.text,'Keep');assert.equal(stock.frames[0].bounds.width,.2);
 await T.apply(stock,{colorIdentity:'BG'});assert.equal(stock.frames[0].src,'/img/frames/m15/regular/m15PTM.png','Multicolor stock badge follows regular CSV behavior');
 stock.text.type.text='Artifact Creature';await T.apply(stock,{color:'U'});assert.equal(stock.frames[0].src,'/img/frames/m15/regular/m15PTU.png','Colored artifacts keep the identity-colored badge');
 const custom=clone(source);custom.frames=[clone(source.frames[0])];custom.frames[0].src='/img/frames/m15/regular/m15PTM.png';await T.apply(custom,{color:'U'});assert.ok(custom.frames[0].src.startsWith('data:'),'An explicit custom family overrides automatic stock behavior');T.unlink(custom.frames[0]);assert.ok(custom.templateThemes.families.length,'Unlinking leaves the family available');await T.apply(custom,{color:'U'});assert.equal(custom.frames[0].src,'/img/frames/m15/regular/m15PTU.png','Removing the family re-enables stock lookup');
 const sectionCalls=[];context.FrameSectionCatalog={styles:[{id:'battle',sourcePack:'Battle',variants:{u:{src:'native-blue'}}},{id:'borderless',variants:{u:{src:'native-rules'}}}]};context.FrameSectionTools={renderStyle:async(...args)=>{sectionCalls.push(args);return{src:asset('blue',.5).src};},renderPrototype:async()=>({src:asset('blue').src,extras:{mana:{src:asset('blue').src}}}),renderCrownArtwork:async()=>asset('blue').src};
 const mixed={width:100,height:100,text:{},frames:[{designLayerId:'title',componentKind:'Title',designSourcePack:'Battle',bossSymbolCleared:true,resizeContainerRaster:true,bounds:{x:.1,y:.1,width:.8,height:.1},src:'old-title'}, {designLayerId:'rules',sectionAppearance:{style:'borderless',role:'rules',pinlines:false},sectionModule:{partId:'proto'},bounds:{x:.1,y:.6,width:.8,height:.3},src:'old-rules'}, {designLayerId:'proto',bounds:{x:.1,y:.8,width:.8,height:.1},src:'old-prototype'}, {designLayerId:'crown',sectionCrown:{owner:'title',type:'auto',backing:true},bounds:{x:.1,y:.05,width:.8,height:.1},src:'old-crown'}, {designLayerId:'custom',src:'custom-border',bounds:{x:0,y:0,width:1,height:1}}]};const geometry=clone(mixed.frames.map(frame=>frame.bounds));await T.apply(mixed,{color:'U'});assert.deepEqual(mixed.frames.map(frame=>frame.bounds),geometry);assert.equal(mixed.frames[4].src,'custom-border','Unrecognized custom artwork stays unchanged');assert.equal(sectionCalls[0][6].clearSymbol,true,'Recoloring a replaced transform title keeps the old glyph removed');assert.equal(mixed.frames[2].stockThemeRecipe.kind,'prototype');assert.equal(mixed.frames[3].stockThemeRecipe.kind,'crown');assert.equal(mixed.frames[1].stockThemeRecipe.style,'borderless','Transparent style is retained');
 // Class frames contain several regions in one image, including legacy full right-half overlays.
 const realFix=context.fixUri;
 const classMask=role=>{const c=createCanvas(100,100),ctx=c.getContext('2d');ctx.fillStyle='white';const areas={maskPinlines:[0,0,100,10],maskRules:[0,50,100,40],maskTextBoxes:[0,50,100,40],maskTitle:[0,10,100,10],maskType:[0,20,100,10]};ctx.fillRect(...areas[role]);return c.toDataURL();};
 context.fixUri=src=>/^\/img\/frames\/class\/(?:nyx\/)?[a-z]\.png$/.test(src)?asset({b:'black',g:'green',u:'blue',m:'gold',a:'gray'}[src.match(/([a-z])\.png$/)[1]]||'white').src:/class\/masks\//.test(src)?classMask(src.match(/(mask\w+)\.png$/)[1]):realFix(src);
 const classTemplate={version:'classRange',width:100,height:100,text:{type:{text:'Enchantment Class'},level:{text:'Keep',x:.5}},frames:[{name:'Green Frame',src:'/img/frames/class/nyx/g.png',masks:[{name:'Right Half',src:'/img/frames/maskRightHalf.png'}],bounds:{x:0,y:0,width:1,height:1}}, {name:'Black Frame — Rules',componentKind:'Rules',src:'/img/frames/class/nyx/b.png',masks:[{name:'Rules',src:'/img/frames/class/masks/maskRules.png'}]}],rulesRanges:[{kind:'class',modules:[{id:'level-1'}]}]};
 await T.apply(classTemplate,{color:'Multicolor',colorIdentity:'BG'});assert.deepEqual(await pixel(classTemplate.frames[0].src,50,15),[255,215,0,255],'Whole Class title stays gold');assert.deepEqual(await pixel(classTemplate.frames[0].src,50,35),[255,215,0,255],'Class body stays gold');assert.ok((await pixel(classTemplate.frames[0].src,99,55))[1]>120,'Legacy whole right-half Class overlay contains the split rules');assert.ok((await pixel(classTemplate.frames[0].src,99,5))[1]>120,'Class pinlines split');assert.equal(classTemplate.rulesRanges[0].modules[0].id,'level-1');assert.equal(classTemplate.text.level.text,'Keep');
 classTemplate.text.type.text='Artifact Enchantment Class';await T.apply(classTemplate,{colorIdentity:'U'});assert.deepEqual(await pixel(classTemplate.frames[0].src,50,35),[128,128,128,255],'Colored artifact Class body is artifact gray');assert.deepEqual(await pixel(classTemplate.frames[0].src,50,15),[0,0,255,255],'Colored artifact Class title follows its identity');
 const classFix=context.fixUri;context.fixUri=src=>/m15Frame[A-Z]\.png$/.test(src)?classFix('/img/frames/class/'+src.match(/([A-Z])\.png$/)[1].toLowerCase()+'.png'):/m15Mask(Pinline|Rules|Title|Type)\.png$/.test(src)?classMask('mask'+src.match(/m15Mask(\w+)\.png$/)[1].replace('Pinline','Pinlines')):classFix(src);
 const legacy={text:{type:{text:'Creature'}},frames:[{name:'Black Frame',src:'/img/frames/m15/regular/m15FrameB.png',masks:[]}]};await T.apply(legacy,{colorIdentity:'BG'});assert.deepEqual(await pixel(legacy.frames[0].src,50,35),[255,215,0,255],'Captured older regular frames use gold bodies');assert.ok((await pixel(legacy.frames[0].src,99,55))[1]>120,'Captured older regular frames use split rules');context.fixUri=classFix;
 const familyClass={text:{},rulesRanges:[{kind:'class',visualFamilies:{header:{variants:{m:asset('gold'),u:asset('blue')}}}}],frames:[{name:'Level 2 Header',componentKind:'Title',visualFamilyId:'header',src:'saved',bounds:{x:0,y:0,width:1,height:1}}]};await T.apply(familyClass,{colorIdentity:'BG'});assert.deepEqual(await pixel(familyClass.frames[0].src,50,50),[255,215,0,255],'Class appearance families participate in CSV themes');const absentWarnings=[];await T.apply(familyClass,{colorIdentity:'R'},absentWarnings);assert.match(absentWarnings[0],/missing Red/);context.fixUri=realFix;
 // The built-in layer builder uses the same policy, including hybrid/older styles.
 const creator=fs.readFileSync('js/creator-23.js','utf8'),auto=fs.readFileSync('js/autoFrame.js','utf8');
 const builder=vm.createContext({console,document:{querySelector:()=>({checked:false})},getFrameTypeConfig:()=>({supportsCrown:true,supportsPT:true,makeFrameFunction:(letter,role,right)=>({letter,role,right})})});
 vm.runInContext(creator.slice(creator.indexOf('function cardFrameProperties('),creator.indexOf('function setAutoframeNyx(')),builder);
 vm.runInContext(auto.slice(auto.indexOf('function buildAutoFrames('),auto.indexOf('async function autoFrameUnified(')),builder);
 for(const style of ['M15Regular-1','Vault','JapanShowcase','Seventh','Etched'])for(const type of ['Legendary Creature','Legendary Artifact Creature']){
  const frames=builder.buildAutoFrames(style,['B','G'],'{b/g}',type,'4/4'),parts=role=>frames.filter(frame=>frame.role===role);
  for(const role of style==='Seventh'?['Frame','PT']:['Frame','Title','Type','PT']){assert.equal(parts(role).length,1);assert.equal(parts(role)[0].letter,role==='Frame'&&type.includes('Artifact')?'A':'M',style+' '+role);}
  for(const role of ['Pinline','Crown','Rules'])assert.deepEqual(Array.from(parts(role),frame=>frame.letter).sort(),['B','G'],style+' split '+role);
 }
 const monoArtifact=builder.buildAutoFrames('M15Regular-1',['U'],'{u}','Artifact Creature','1/1');for(const frame of monoArtifact.filter(frame=>['Frame','Title','Type','PT','Rules','Pinline'].includes(frame.role)))assert.equal(frame.letter,frame.role==='Frame'?'A':'U');
 // Exercise the actual CSV named-template path, not a duplicate implementation.
 const csv=fs.readFileSync('js/csvCardBuilder.js','utf8'),section=(from,to)=>csv.slice(csv.indexOf(from),csv.indexOf(to,csv.indexOf(from)));
 Object.assign(context,{namedTemplateCache:{},FrameProjectStore:{getProjectCardByName:async()=>clone(source)},cloneSerializableCard:clone,applyCoreFields(){},applyCustomTextboxes(){},applyCollectorFields(){}});
 vm.runInContext(section('async function applyNamedProjectTemplate(', 'function layoutPackForFrameType('),context);
 const result={fields:{template:'Boss Frame',color:'WU'},card:{csvImport:{sourceRow:2}},templateFields:{'prototype rules':['Imported prototype']},warnings:[]};await context.applyNamedProjectTemplate(result);assert.equal(result.appliedTemplateName,'Boss Frame');assert.equal(result.card.text.random.text,'Imported prototype');assert.deepEqual(Array.from(result.card.csvImport.templateColors),['w','u']);assert.equal(source.frames[0].src,'original','Cached template is not mutated');
 vm.runInContext(section('function collectMappedRow(', 'function applyCoreFields('),context);
 const row=context.collectMappedRow({rows:[['  Ability  ','']],headers:['Prototype Rules','Empty'],mappings:['templatefield:prototype rules','templatefield:empty']},0);assert.equal(row.templateFields['prototype rules'][0],'Ability');assert.equal(row.templateFields.empty[0],'','Blank mapped values explicitly clear template text');
 if(process.env.TEMPLATE_THEME_PROJECT_FIXTURE){const project=JSON.parse(fs.readFileSync(process.env.TEMPLATE_THEME_PROJECT_FIXTURE,'utf8'));project.templateThemes.autoStock=false;const savedPipeline=project.frames.find(frame=>/Black.*Rules container/.test(frame.name)).src;const geometry=JSON.stringify(project.frames.map(frame=>frame.bounds)),text=JSON.stringify(project.text),ranges=JSON.stringify(project.rulesRanges);await T.apply(project,{color:'WU'});const right=project.frames.find(frame=>/Green.*Right Half.*Rules container/.test(frame.name)),left=project.frames.find(frame=>/Black.*Rules container/.test(frame.name));assert.equal(right.hidden,true);assert.ok(left.src.startsWith('data:image/png'));for(const [x,y] of [[50,19],[1,50],[98,50],[50,91]]){const before=await pixel(savedPipeline,x,y),after=await pixel(left.src,x,y);assert.ok(Math.abs(before[3]-after[3])<20,'Uploaded pipeline preserves the saved stroke at '+x+','+y);}assert.equal(JSON.stringify(project.frames.map(frame=>frame.bounds)),geometry);assert.equal(JSON.stringify(project.text),text);assert.equal(JSON.stringify(project.rulesRanges),ranges);console.log('PASS: uploaded Boss template keeps geometry/text/ranges and suppresses the matching right-half overlay.');}
 console.log('PASS: theme colors/splits, alpha, card-coordinate blending, preserved geometry/content, atomic errors, label mappings and named CSV templates.');
})().catch(error=>{console.error(error);process.exitCode=1;});
