const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createCanvas,Image}=require('@napi-rs/canvas');
const document={readyState:'loading',addEventListener(){},querySelector(){return null;},createElement(tag){assert.equal(tag,'canvas');return createCanvas(1,1);}};
const mask=createCanvas(100,100),maskctx=mask.getContext('2d');for(let x=0;x<100;x++){maskctx.fillStyle=`rgba(0,0,0,${x/99})`;maskctx.fillRect(x,0,1,100);}
const context={document,Image,console,window:null,addEventListener(){},fixUri:src=>src==='/img/frames/maskRightHalf.png'?mask.toDataURL():/^\/img\/.*(?:m15PT|\/pt)[A-Z]\.png$/.test(src)?asset(src.includes('U.png')?'blue':'gold').src:src};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('js/templateThemes.js','utf8'),context);const T=context.TemplateThemes;
const clone=value=>JSON.parse(JSON.stringify(value));
function asset(color,alpha=1){const canvas=createCanvas(100,100),ctx=canvas.getContext('2d');ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.fillRect(0,0,100,100);return {src:canvas.toDataURL()};}
const source={width:2814,height:2010,artBounds:{x:.1,y:.2,width:.8,height:.3},text:{random:{name:'Prototype Rules',text:'Old',x:.1,size:.03}},rulesRanges:[{bounds:{x:.1,y:.5,width:.8,height:.4}}],templateThemes:{enabled:true,families:[{id:'pin',name:'Pinline',variants:{w:asset('white'),u:asset('blue'),b:asset('black'),r:asset('red',.5),g:asset('green',.5),c:asset('gray'),m:asset('gold')}}]},frames:[{name:'Pinline',src:'original',bounds:{x:0,y:0,width:1,height:1},opacity:70,templateTheme:{familyId:'pin',side:'full',masks:[]}}, {name:'Fixed',src:'fixed',bounds:{x:.2,y:.2,width:.1,height:.1}}]};
async function pixel(src,x,y){const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=src;});const c=createCanvas(100,100);c.getContext('2d').drawImage(img,0,0,100,100);return [...c.getContext('2d').getImageData(x,y,1,1).data];}
(async()=>{
 assert.equal(T.selection({color:'unknown',frameLeftColor:'U'}).left,'u','Explicit color takes precedence');assert.equal(T.selection({color:'WUBRG'}).left,'m');assert.equal(T.selection({color:'Colorless'}).left,'c');assert.equal(T.selection({colorIdentity:'Blue Black'}).right,'b');assert.throws(()=>T.selection({frameLeftColor:'WU'}),/one color/);assert.throws(()=>T.selection({frameRightColor:'G'}),/requires/);assert.throws(()=>T.colors('purple'),/Unknown/);
 for(const color of ['W','U','B','R','G','C','M','WU','UB','BR','RG','GW','WB','UR','BG','RW','GU']){const data=clone(source);await T.apply(data,{color});assert.deepEqual(data.frames[0].bounds,source.frames[0].bounds);assert.deepEqual(data.artBounds,source.artBounds);assert.deepEqual(data.rulesRanges,source.rulesRanges);assert.deepEqual(data.text,source.text);assert.equal(data.frames[1].src,'fixed');assert.equal(data.frames[0].opacity,70);}
 const split=clone(source);await T.apply(split,{frameLeftColor:'R',frameRightColor:'G'});const mid=await pixel(split.frames[0].src,50,50);assert.ok(mid[3]>=125&&mid[3]<=130,'Complementary split blending preserves translucent alpha');assert.ok(mid[0]>100&&mid[1]>45,'Both colors contribute at the seam');
 const right=clone(source);right.frames[0].bounds={x:.75,y:0,width:.25,height:1};await T.apply(right,{color:'WU'});const edge=await pixel(right.frames[0].src,0,50);assert.ok(edge[2]>180,'Blend follows card coordinates instead of restarting at each layer');
 const missing=clone(source);missing.frames.push({name:'Missing',templateTheme:{familyId:'other'},src:'stay'});const before=JSON.stringify(missing);await assert.rejects(T.apply(missing,{color:'W'}),/Missing asset family/);assert.equal(JSON.stringify(missing),before,'A failing layer leaves the entire template unchanged');
 const absent=clone(source);await assert.rejects(T.apply(absent,{color:'Artifact'}),/missing Artifact/);assert.equal(absent.frames[0].src,'original');await T.apply(absent,{});assert.equal(absent.frames[0].src,'original','Blank color retains the saved appearance');
 const disabled=clone(source);disabled.templateThemes.enabled=false;disabled.templateThemes.autoStock=false;await T.apply(disabled,{color:'purple'});assert.equal(disabled.frames[0].src,'original');
 const fields=clone(source),warnings=[];T.mapFields(fields,{'prototype rules':['New rules']},warnings);assert.equal(fields.text.random.text,'New rules');fields.text.second={name:'Prototype Rules',text:'Keep'};T.mapFields(fields,{'prototype rules':['Ambiguous']},warnings);assert.equal(fields.text.random.text,'New rules');assert.match(warnings[0],/ambiguous/);
 fields.frames[0].templateTheme.masks=[{src:'data:mask'}];assert.equal(T.records(fields).length,8,'Project records include every variant and linked mask');T.restore(fields.frames[0],{src:fields.frames[0].src});assert.equal(fields.frames[0].templateTheme,undefined,'Undo removes newly added links');
 // Stock elements work without enabling custom families or uploading stock assets.
 const stock={width:100,height:100,text:{type:{text:'Creature'},rules:{text:'Keep'}},frames:[{designLayerId:'pt',name:'Power/Toughness',src:'/img/frames/m15/regular/m15PTM.png',bounds:{x:.7,y:.8,width:.2,height:.1},rotation:15,opacity:60,masks:[]}],rulesRanges:[]};
 await T.apply(stock,{colorIdentity:'U'});assert.equal(stock.frames[0].src,'/img/frames/m15/regular/m15PTU.png');assert.equal(stock.frames[0].rotation,15);assert.equal(stock.frames[0].opacity,60);assert.equal(stock.text.rules.text,'Keep');assert.equal(stock.frames[0].bounds.width,.2);
 await T.apply(stock,{colorIdentity:'BG'});assert.equal(stock.frames[0].src,'/img/frames/m15/regular/m15PTM.png','Multicolor stock badge follows regular CSV behavior');
 stock.text.type.text='Artifact Creature';await T.apply(stock,{color:'U'});assert.equal(stock.frames[0].src,'/img/frames/m15/regular/m15PTA.png');
 const custom=clone(source);custom.frames=[clone(source.frames[0])];custom.frames[0].src='/img/frames/m15/regular/m15PTM.png';await T.apply(custom,{color:'U'});assert.ok(custom.frames[0].src.startsWith('data:'),'An explicit custom family overrides automatic stock behavior');T.unlink(custom.frames[0]);assert.ok(custom.templateThemes.families.length,'Unlinking leaves the family available');await T.apply(custom,{color:'U'});assert.equal(custom.frames[0].src,'/img/frames/m15/regular/m15PTU.png','Removing the family re-enables stock lookup');
 const sectionCalls=[];context.FrameSectionCatalog={styles:[{id:'battle',sourcePack:'Battle',variants:{u:{src:'native-blue'}}},{id:'borderless',variants:{u:{src:'native-rules'}}}]};context.FrameSectionTools={renderStyle:async(...args)=>{sectionCalls.push(args);return{src:asset('blue',.5).src};},renderPrototype:async()=>({src:asset('blue').src,extras:{mana:{src:asset('blue').src}}}),renderCrownArtwork:async()=>asset('blue').src};
 const mixed={width:100,height:100,text:{},frames:[{designLayerId:'title',componentKind:'Title',designSourcePack:'Battle',bossSymbolCleared:true,resizeContainerRaster:true,bounds:{x:.1,y:.1,width:.8,height:.1},src:'old-title'}, {designLayerId:'rules',sectionAppearance:{style:'borderless',role:'rules',pinlines:false},sectionModule:{partId:'proto'},bounds:{x:.1,y:.6,width:.8,height:.3},src:'old-rules'}, {designLayerId:'proto',bounds:{x:.1,y:.8,width:.8,height:.1},src:'old-prototype'}, {designLayerId:'crown',sectionCrown:{owner:'title',type:'auto',backing:true},bounds:{x:.1,y:.05,width:.8,height:.1},src:'old-crown'}, {designLayerId:'custom',src:'custom-border',bounds:{x:0,y:0,width:1,height:1}}]};const geometry=clone(mixed.frames.map(frame=>frame.bounds));await T.apply(mixed,{color:'U'});assert.deepEqual(mixed.frames.map(frame=>frame.bounds),geometry);assert.equal(mixed.frames[4].src,'custom-border','Unrecognized custom artwork stays unchanged');assert.equal(sectionCalls[0][6].clearSymbol,true,'Recoloring a replaced transform title keeps the old glyph removed');assert.equal(mixed.frames[2].stockThemeRecipe.kind,'prototype');assert.equal(mixed.frames[3].stockThemeRecipe.kind,'crown');assert.equal(mixed.frames[1].stockThemeRecipe.style,'borderless','Transparent style is retained');
 // Exercise the actual CSV named-template path, not a duplicate implementation.
 const csv=fs.readFileSync('js/csvCardBuilder.js','utf8'),section=(from,to)=>csv.slice(csv.indexOf(from),csv.indexOf(to,csv.indexOf(from)));
 Object.assign(context,{namedTemplateCache:{},FrameProjectStore:{getProjectCardByName:async()=>clone(source)},cloneSerializableCard:clone,applyCoreFields(){},applyCustomTextboxes(){},applyCollectorFields(){}});
 vm.runInContext(section('async function applyNamedProjectTemplate(', 'function layoutPackForFrameType('),context);
 const result={fields:{template:'Boss Frame',color:'WU'},card:{csvImport:{sourceRow:2}},templateFields:{'prototype rules':['Imported prototype']},warnings:[]};await context.applyNamedProjectTemplate(result);assert.equal(result.appliedTemplateName,'Boss Frame');assert.equal(result.card.text.random.text,'Imported prototype');assert.deepEqual(Array.from(result.card.csvImport.templateColors),['w','u']);assert.equal(source.frames[0].src,'original','Cached template is not mutated');
 vm.runInContext(section('function collectMappedRow(', 'function applyCoreFields('),context);
 const row=context.collectMappedRow({rows:[['  Ability  ','']],headers:['Prototype Rules','Empty'],mappings:['templatefield:prototype rules','templatefield:empty']},0);assert.equal(row.templateFields['prototype rules'][0],'Ability');assert.equal(row.templateFields.empty[0],'','Blank mapped values explicitly clear template text');
 console.log('PASS: theme colors/splits, alpha, card-coordinate blending, preserved geometry/content, atomic errors, label mappings and named CSV templates.');
})().catch(error=>{console.error(error);process.exitCode=1;});
