const fs=require('fs'),vm=require('vm');
const defs=[['regular','Regular','M15RegularNew'],['borderless','Showcase — Borderless (transparent)','GenericShowcase'],['borderless-alt','Showcase — Borderless (Alt)','Borderless'],['clear','Clear Textboxes','M15ClearTextboxes'],['transform-front','Transform — front','M15TransformFront'],['transform-back','Transform — back','M15TransformBackNew'],['battle','Battle','Battle'],['adventure','Adventure','Adventure'],['prototype','Prototype','Prototype']];
function pack(name){const source=fs.readFileSync('js/frames/pack'+name+'.js','utf8');const ctx={};vm.runInNewContext(source.slice(0,source.indexOf('document.querySelector')),ctx);return ctx.availableFrames;}
function color(name){const colors={white:'w',blue:'u',black:'b',red:'r',green:'g',multicolored:'m',multicolor:'m',artifact:'a',land:'l',colorless:'c',vehicle:'v'};return colors[name.toLowerCase().split(' ')[0]];}
const catalog=defs.map(([id,label,sourcePack])=>{const frames=pack(sourcePack),variants={};for(const frame of frames){const suitable=id==='prototype'?/Prototype Rules$/.test(frame.name):/^(White|Blue|Black|Red|Green|Multicolor(?:ed)?|Artifact|Land|Colorless|Vehicle) Frame$/.test(frame.name);if(!suitable)continue;variants[color(frame.name)]={src:frame.src,bounds:frame.bounds||{x:0,y:0,width:1,height:1},masks:frame.masks||[]};if(id==='prototype'){variants[color(frame.name)].extras=frames.filter(item=>item.name.startsWith(frame.name.split(' ')[0]+' Prototype ')&&(/Mana Cost \(Short\)|P\/T$/.test(item.name))).map(item=>({src:item.src,bounds:item.bounds||{x:0,y:0,width:1,height:1},masks:[]}));}}
return{id,label,sourcePack,roles:id==='prototype'?['rules']:['title','rules'],variants};});
const crowns={};for(const [key,name]of[['regular','M15LegendCrownsNew'],['transform-front','TransformLegendCrowns'],['transform-back','TransformLegendCrowns']]){crowns[key]={};for(const frame of pack(name)){if(!/Legend Crown/.test(frame.name)||/Cover/.test(frame.name))continue;const back=/\(Back\)/.test(frame.name);if(key==='transform-front'&&back||key==='transform-back'&&!back)continue;crowns[key][color(frame.name)]={src:frame.src,bounds:frame.bounds,masks:frame.masks};}}
const crownCovers={};for(const[key,name]of[['regular','M15LegendCrownsNew'],['transform-front','TransformLegendCrowns'],['transform-back','TransformLegendCrowns']]){const cover=pack(name).find(frame=>frame.name==='Legend Crown Border Cover');crownCovers[key]={src:cover.src,bounds:cover.bounds};}
fs.writeFileSync('js/frameSectionCatalog.js','// Shared section assets sourced from the existing frame packs.\nwindow.FrameSectionCatalog = '+JSON.stringify({styles:catalog,crowns,crownCovers},null,2)+';\n');
